---
- name: Validate Repo runners
  user: ansible
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    runner_user: ansible
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    runner_org: yes
    github_api_url: "https://api.github.com"
    access_token: "{{ lookup('env', 'PERSONAL_ACCESS_TOKEN') }}"
    runner_name: "{{ ansible_facts.hostname }}"

  tasks:
    - name: Give the runners a minute
      ansible.builtin.pause:
        seconds: 30

    - name: Check currently registered runners
      ansible.builtin.uri:
        url: "{{ github_api_url }}/orgs/{{ github_owner | default(github_account) }}/actions/runners"
        headers:
          Authorization: "token {{ access_token }}"
          Accept: "application/vnd.github.v3+json"
        method: GET
        status_code: 200
        force_basic_auth: yes
      register: registered_runners

    - name: Check Runner
      ansible.builtin.assert:
        that:
          - registered_runners.json.runners.0.status == "offline"
        quiet: true
