#!/bin/sh

export AWS_REGION=us-east-1
export AWS_ACCESS_KEY_ID="$(op read op://Private/AWS\ Personal/AWS_ACCESS_KEY_ID --account my.1password.com)"
export AWS_SECRET_ACCESS_KEY="$(op read op://Private/AWS\ Personal/AWS_SECRET_ACCESS_KEY --account my.1password.com)"
export CLOUDFLARE_TUNNEL_SECRET="$(op read op://Private/homelab/cloudflaretunnelsecret --account my.1password.com)"
export NOMAD_TOKEN="$(op read op://Private/homelab/nomadclienttoken --account my.1password.com)"
