#!/bin/sh

# https://github.com/ansible/ansible/issues/32499
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

export AWS_REGION=us-east-1
export AWS_ACCESS_KEY_ID="$(op read op://Private/AWS\ Personal/AWS_ACCESS_KEY_ID --account my.1password.com)"
export AWS_SECRET_ACCESS_KEY="$(op read op://Private/AWS\ Personal/AWS_SECRET_ACCESS_KEY --account my.1password.com)"
export CLOUDFLARE_EMAIL="$(op read op://Private/homelab/cloudflareemail --account my.1password.com)"
export CLOUDFLARE_API_KEY="$(op read op://Private/homelab/cloudflareapikey --account my.1password.com)"
export CLOUDFLARE_TUNNEL_SECRET="$(op read op://Private/homelab/cloudflaretunnelsecret --account my.1password.com)"
export DOCKER_PASSWORD="$(op read op://Private/homelab/dockerpassword --account my.1password.com)"

export CONSUL_TOKEN="$(op read op://Private/homelab/consulmgmttoken --account my.1password.com)"
export NOMAD_TOKEN="$(op read op://Private/homelab/nomadmgmttoken --account my.1password.com)"
export MINIO_PASSWORD="$(op read op://Private/homelab/minioadminpassword --account my.1password.com)"

# ansible
export CONSUL_ACL_MASTER_TOKEN="$CONSUL_TOKEN"
export CONSUL_ENCRYPT_KEY="$(op read op://Private/homelab/consulencryptkey --account my.1password.com)"

# tf
export TF_VAR_cloudflare_account_id="$(op read op://Private/homelab/cloudflareaccountid --account my.1password.com)"
export TF_VAR_cloudflare_zone_id="$(op read op://Private/homelab/cloudflarezoneid --account my.1password.com)"
export TF_VAR_cloudflare_domain="$(op read op://Private/homelab/cloudflaredomain --account my.1password.com)"
export TF_VAR_github_idp_client_id="$(op read op://Private/homelab/githuboidcclientid --account my.1password.com)"
export TF_VAR_github_idp_client_secret="$(op read op://Private/homelab/githuboidcclientsecret --account my.1password.com)"
export TF_VAR_minio_access_key="$(op read op://Private/homelab/minioaccesskey --account my.1password.com)"
export TF_VAR_minio_secret_key="$(op read op://Private/homelab/miniosecretkey --account my.1password.com)"
export TF_VAR_nr_api_key="$(op read op://Private/homelab/NR_API_KEY --account my.1password.com)"
