---
# https://cert-manager.io/docs/installation/helm/
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: default
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  targetNamespace: default
  set:
  valuesContent: |-
    crds:
      enabled: true