---
- hosts: ser
  become: true
  
  pre_tasks:
    - name: Check if the file already exists
      stat:
        path: /etc/systemd/resolved.conf.d/consul.conf
      register: conf_file

    # https://developer.hashicorp.com/consul/tutorials/networking/dns-forwarding#systemd-resolved-setup
    - name: Create the destination directory if it doesn't exist
      file:
        path: /etc/systemd/resolved.conf.d
        state: directory
      when: not conf_file.stat.exists

    - name: Config systemd-resolved for consul
      copy:
        content: |
          [Resolve]
          DNS=127.0.0.1:8600
          DNSSEC=false
          Domains=~consul
        dest: /etc/systemd/resolved.conf.d/consul.conf

    - name: Restart systemd-resolved
      ansible.builtin.systemd:
        state: restarted
        enabled: true
        daemon_reload: true
        name: systemd-resolved

  roles:
    - role: ../roles/ansible-consul
      vars:
        auto_encrypt:
          enabled: true
        consul_node_role: server
        consul_group_name: ser
        consul_version: 1.17.1

        consul_acl_enable: true
        consul_acl_master_token_display: true
        consul_autopilot_enable: true
        consul_bootstrap_expect: true
        consul_bootstrap_expect_value: 3
        consul_client_address: 0.0.0.0
        consul_configd_path: /etc/consul

        consul_tls_enable: true
        consul_ports_https: 8501
        consul_ports_grpc_tls: 8503
        consul_tls_ca_crt: consul-agent-ca.pem
        consul_tls_server_crt: dc1-server-consul-0.pem
        consul_tls_server_key: dc1-server-consul-0-key.pem
        consul_tls_verify_incoming: false
        consul_tls_verify_incoming_https: false
        consul_tls_verify_incoming_rpc: true

        consul_config_custom:
          tls:
            grpc:
              verify_incoming: false
          telemetry:
            prometheus_retention_time: 1m
          ui_config:
            enabled: true
            content_path: /consul
