---
apiVersion: v1
kind: Secret
metadata:
  name: "headlamp-admin"
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "headlamp-admin"   
type: kubernetes.io/service-account-token  