---
# https://www.suse.com/support/kb/doc/?id=000020082
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: minio
  namespace: default
spec:
  chart: minio
  repo: https://charts.min.io/
  targetNamespace: default
  set:
  # https://github.com/minio/minio/blob/master/helm/minio/values.yaml
  valuesContent: |-
    image:
      tag: RELEASE.2024-10-13T13-34-11Z

    extraArgs:
      - "--json"

    environment:
      MINIO_BROWSER_LOGIN_ANIMATION: "off"

    replicas: 3

    rootUser: minio
    rootPassword: ${minio_admin_password}

    persistence:
      enabled: true
      storageClass: "local-storage"
      size: 1.78Ti

    securityContext:
      enabled: true
      runAsUser: 0
      runAsGroup: 2
      fsGroup: 2

    resources:
      requests:
        memory: 8Gi

    users:
      - accessKey: ${minio_access_key}
        secretKey: ${minio_secret_key}
        policy: readwrite
