# https://kubernetes.io/docs/concepts/storage/volumes/#local
# https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
# https://github.com/minio/operator?tab=readme-ov-file#tenant-persistent-volumes
%{ for node in split(",", nodes) }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sata-${node}
spec:
  capacity:
    storage: 1.8Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/sata
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${node}
%{ endfor }
---
# https://kubernetes.io/docs/concepts/storage/storage-classes/
# https://github.com/minio/operator?tab=readme-ov-file#tenant-storage-class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
%{ for vol in split(",", arr_volumes) }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-config-${vol}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: arr-config-${vol}
  local:
    path: /usr/local/var/config/${vol}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ser5-3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arr-config-${vol}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
%{ endfor }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-cache
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: arr-cache
  local:
    path: /usr/local/var/cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ser5-3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arr-cache
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
%{ for vol in split(",", arr_volumes) }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-downloads-${vol}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: arr-downloads-${vol}
  local:
    path: /usr/local/var/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ser5-3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arr-downloads-${vol}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-movies-${vol}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: arr-movies-${vol}
  local:
    path: /usr/local/var/movies
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ser5-3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arr-movies-${vol}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-tv-${vol}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: arr-tv-${vol}
  local:
    path: /usr/local/var/tv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ser5-3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arr-tv-${vol}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
%{ endfor }