- name: Install CloudFlare Tunnel
  hosts: ser
  become: true
  tasks:
    # Set up Cloud Flare Tunnel
    # https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/install-and-setup/tunnel-guide/local/
    - name: Add cloudflared
      ansible.builtin.apt:
        deb: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
    # This skips the initial "cloudflared service install" command
    - name: Start cloudflared
      ansible.builtin.systemd:
        state: restarted
        enabled: true
        daemon_reload: true
        name: cloudflared
