---
- import_playbook: ./tasks/tailscaled.yaml
- import_playbook: ./tasks/sudoless.yaml
- import_playbook: ./tasks/pihole.yaml
- import_playbook: ./tasks/docker.yaml
- import_playbook: ./tasks/cloudflared.yaml
- import_playbook: ./tasks/consul.yaml
- import_playbook: ./tasks/nomad.yaml
- import_playbook: ./tasks/logrotate.yaml
