- name: Set up systemd-resolved for pihole
  hosts: ser
  become: true

  # https://github.com/pi-hole/docker-pi-hole#installing-on-ubuntu-or-fedora
  tasks:
    - name: Update DNSStubListener in resolved.conf
      ansible.builtin.shell: |
        sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf
      args:
        creates: /etc/systemd/resolved.conf.orig
      notify: Restart systemd-resolved

    - name: Update resolv.conf symlink
      ansible.builtin.shell: |
        sh -c 'rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'
      args:
        creates: /etc/resolv.conf
      notify: Restart systemd-resolved

  handlers:
    - name: Restart systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
