---
- name: Cleanup
  user: ansible
  hosts: all
  become: yes
  vars:
    runner_user: ansible
    github_repo: "{{ lookup('env', 'GITHUB_REPO') }}"
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    runner_state: absent
  roles:
    - monolithprojects.github_actions_runner
